In [1]:
import pandas as pd
import numpy as np
import re
import os

In [2]:
def clean_str(string):
   
    string = re.sub(r"\'s", "", string)
    string = re.sub(r"\'ve", "", string)
    string = re.sub(r"n\'t", "", string)
    string = re.sub(r"\'re", "", string)
    string = re.sub(r"\'d", "", string)
    string = re.sub(r"\'ll", "", string)
    string = re.sub(r",", "", string)
    string = re.sub(r"!", " ! ", string)
    string = re.sub(r"\(", "", string)
    string = re.sub(r"\)", "", string)
    string = re.sub(r"\?", "", string)
    string = re.sub(r"'", "", string)
    string = re.sub(r"[^A-Za-z0-9(),!?\'\`]", " ", string)
    string = re.sub(r"[0-9]\w+|[0-9]","", string)
    string = re.sub(r"\s{2,}", " ", string)
    return string.strip().lower()


In [3]:
pwd

'/media/pratikshit/6CBAB0B1BAB078E2/DIH/DIH/Preprocessing'

In [6]:
dataset=pd.read_csv("../dataset/bbc/newdatasets.csv")

In [7]:
dataset

news        type
0     Ad sales boost Time Warner profit\n\nQuarterly...    business
1     Dollar gains on Greenspan speech\n\nThe dollar...    business
2     Yukos unit buyer faces loan claim\n\nThe owner...    business
3     High fuel prices hit BA's profits\n\nBritish A...    business
4     Pernod takeover talk lifts Domecq\n\nShares in...    business
...                                                 ...         ...
2220  BT program to beat dialler scams\n\nBT is intr...  technology
2221  Spam e-mails tempt net shoppers\n\nComputer us...  technology
2222  Be careful how you code\n\nA new European dire...  technology
2223  US cyber security chief resigns\n\nThe man mak...  technology
2224  Losing yourself in online gaming\n\nOnline rol...  technology

[2225 rows x 2 columns]

In [8]:
x=dataset["news"].tolist()
y=dataset["type"].tolist()

In [11]:
len(x)

2225

In [12]:
x

['Ad sales boost Time Warner profit\n\nQuarterly profits at US media giant TimeWarner jumped 76% to $1.13bn (£600m) for the three months to December, from $639m year-earlier.\n\nThe firm, which is now one of the biggest investors in Google, benefited from sales of high-speed internet connections and higher advert sales. TimeWarner said fourth quarter sales rose 2% to $11.1bn from $10.9bn. Its profits were buoyed by one-off gains which offset a profit dip at Warner Bros, and less users for AOL.\n\nTime Warner said on Friday that it now owns 8% of search-engine Google. But its own internet business, AOL, had has mixed fortunes. It lost 464,000 subscribers in the fourth quarter profits were lower than in the preceding three quarters. However, the company said AOL\'s underlying profit before exceptional items rose 8% on the back of stronger internet advertising revenues. It hopes to increase subscribers by offering the online service free to TimeWarner internet customers and will try to si

In [13]:
for index,value in enumerate(x):
    x[index]=clean_str(value)
    

In [14]:
x[0]

'ad sales boost time warner profit quarterly profits at us media giant timewarner jumped to for the three months to december from year earlier the firm which is now one of the biggest investors in google benefited from sales of high speed internet connections and higher advert sales timewarner said fourth quarter sales rose to from its profits were buoyed by one off gains which offset a profit dip at warner bros and less users for aol time warner said on friday that it now owns of search engine google but its own internet business aol had has mixed fortunes it lost subscribers in the fourth quarter profits were lower than in the preceding three quarters however the company said aol underlying profit before exceptional items rose on the back of stronger internet advertising revenues it hopes to increase subscribers by offering the online service free to timewarner internet customers and will try to sign up aol existing customers for high speed broadband timewarner also has to restate an

In [15]:
import nltk
from nltk.corpus import stopwords
from nltk.tokenize import word_tokenize

stop_words=set(stopwords.words('english'))

for index,value in enumerate(x):
    word_tokens=word_tokenize(x[index])
    f=[]
    for word in word_tokens:
        if word not in stop_words:
            f.append(word)
    new_string=""
    for w in f:
        new_string=new_string+w+" "
    x[index]=new_string[:]    

In [16]:
x[0]

'ad sales boost time warner profit quarterly profits us media giant timewarner jumped three months december year earlier firm one biggest investors google benefited sales high speed internet connections higher advert sales timewarner said fourth quarter sales rose profits buoyed one gains offset profit dip warner bros less users aol time warner said friday owns search engine google internet business aol mixed fortunes lost subscribers fourth quarter profits lower preceding three quarters however company said aol underlying profit exceptional items rose back stronger internet advertising revenues hopes increase subscribers offering online service free timewarner internet customers try sign aol existing customers high speed broadband timewarner also restate results following probe us securities exchange commission sec close concluding time warner fourth quarter profits slightly better analysts expectations film division saw profits slump helped box office flops alexander catwoman sharp c

In [17]:
import nltk
from nltk.stem import WordNetLemmatizer

wnl=WordNetLemmatizer()

for index,value in enumerate(x):
     string_lemma=""
     for w in x[index].split():
        string_lemma=string_lemma+wnl.lemmatize(w)+" "
     x[index]=string_lemma[:]   

In [18]:
x[0]

'ad sale boost time warner profit quarterly profit u medium giant timewarner jumped three month december year earlier firm one biggest investor google benefited sale high speed internet connection higher advert sale timewarner said fourth quarter sale rose profit buoyed one gain offset profit dip warner bros le user aol time warner said friday owns search engine google internet business aol mixed fortune lost subscriber fourth quarter profit lower preceding three quarter however company said aol underlying profit exceptional item rose back stronger internet advertising revenue hope increase subscriber offering online service free timewarner internet customer try sign aol existing customer high speed broadband timewarner also restate result following probe u security exchange commission sec close concluding time warner fourth quarter profit slightly better analyst expectation film division saw profit slump helped box office flop alexander catwoman sharp contrast year earlier third final

In [19]:
import scipy
from sklearn.feature_extraction.text import TfidfVectorizer

vect=TfidfVectorizer(min_df=2,stop_words="english")

In [25]:
X=vect.fit_transform(x)
Y=np.array(y)
print("no of features extracted:")
eg, no_features = X.shape
print(no_features)

no of features extracted:
14780


In [36]:
from sklearn.model_selection import train_test_split

train_input, test_input, train_output, test_output = train_test_split(X, Y, test_size=0.2, random_state=25)

print("train input size:", train_input.shape)
print("test input size:", test_input.shape)

train input size: (1780, 14780)
test input size: (445, 14780)


In [30]:
from sklearn.ensemble import RandomForestClassifier

model = RandomForestClassifier(n_estimators=300, max_depth=150, n_jobs=1)
model.fit(train_input, train_output)
predicted_output = model.predict(test_input)

In [32]:
from sklearn.metrics import accuracy_score, cohen_kappa_score, confusion_matrix

ConfusionMatrix = confusion_matrix(test_output, predicted_output)

Accuracy=accuracy_score(test_output, predicted_output)

In [35]:
print("Confusion Matrix:\n", ConfusionMatrix)
print("\nAccuracy: ",Accuracy)

Confusion Matrix:
 [[100   0   2   1   1]
 [  0  77   2   1   0]
 [  2   0  77   1   1]
 [  0   0   1  92   0]
 [  1   1   0   1  84]]

Accuracy:  0.9662921348314607


In [37]:
from sklearn.externals import joblib

joblib.dump(model,"classifier.pkl")
joblib.dump(vect,"vectorizer.pkl")


/home/pratikshit/anaconda3/lib/python3.7/site-packages/sklearn/externals/joblib/__init__.py:15: DeprecationWarning: sklearn.externals.joblib is deprecated in 0.21 and will be removed in 0.23. Please import this functionality directly from joblib, which can be installed with: pip install joblib. If this warning is raised when loading pickled models, you may need to re-serialize those models with scikit-learn 0.21+.
  warnings.warn(msg, category=DeprecationWarning)


['vectorizer.pkl']